"""Initial migration

Revision ID: 306575f0b629
Revises: b51cb15ffbeb
Create Date: 2025-06-23 21:57:30.513335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '306575f0b629'
down_revision = 'b51cb15ffbeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant_pizzas', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant_pizzas', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(),
               existing_nullable=False)

    # ### end Alembic commands ###
